name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: ["22.x"]
        platform: [ubuntu-latest]
    name: Node v${{matrix.node}} ((${{matrix.platform}}))
    runs-on: ${{matrix.platform}}
    defaults:
      run:
        working-directory: packages/aibom
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'
      - name: install root dependencies
        run: pnpm install
        working-directory: .
      - name: build root HTML template
        run: pnpm run build:template
        working-directory: .
      - name: lint code
        run: npm run lint
      - name: build project
        run: npm run build
      - name: run tests
        run: npm run test
      - name: coverage
        uses: codecov/codecov-action@v6
        if: github.actor != 'dependabot[bot]'
        with:
          fail_ci_if_error: true
          verbose: false
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: packages/aibom
        env:
          CI: true

