name: release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write       # to create release (changesets/action)
      issues: write         # to post issue comments (changesets/action)
      pull-requests: write  # to create pull request (changesets/action)
      id-token: write       # to create release (changesets/action)
      packages: write       # to publish to npm (changesets/action)
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          version: 9
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'pnpm'
      - name: Update npm
        run: npm update -g npm
      - name: install root dependencies
        run: pnpm install --frozen-lockfile
      - name: build root HTML template
        run: pnpm run build:template
      - name: build project
        run: npm run build
        working-directory: packages/aibom
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run release
          commit: "chore: new release"
          title: "chore: new release candidate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ''
          NPM_CONFIG_PROVENANCE: true